### ISSUE TITLE
how to build the windows installer?

### ISSUE THREAD

**Issue by liudonghua123** [lombervid/cpython-win-installer#1]
Hi, I read the docs on https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html and it seems do not provide the instructions or guides on how to make the windows installer?

I use `\Tools\msi\build.bat -x86` or `Tools\msi\buildrelease.bat -x86` currently, it only build the executables and a lot of msi.

Could you share your solutions?

**Comment by lombervid** [comment]
Hi. It has been some time since I last touched this, but, iirc, installers are saved in `PCbuild/(win32|amd64)/en-us`. You can find instructions in `Tools/msi/README.txt`.

**Comment by liudonghua123** [comment]
Thanks, I can build the windows installer now using `Tools\msi\buildrelease.bat -x86 -b` and
`Tools\msi\buildrelease.bat -x64 --skip-pgo -b`.

And I have also create a simple project which using github action (https://github.com/liudonghua123/windows-python-installer/blob/main/.github/workflows/build.yml) to create a windows installer.
